### ISSUE TITLE
复现代码出现海底捞针实验长文本训练显存不够的情况

### ISSUE THREAD

**Issue by Kwen-Chen** [FranxYao/Long-Context-Data-Engineering#16]
模型为 Qwen-7B，硬件为 8*A100 80GB
使用了您提供的测试代码，张量并行，但由于不支持 FlashAttention，并没有使用FlashAttention
所能测试海底捞针的文本长度最多到10K，就OOM，想请问一下更多的细节
![image](https://github.com/FranxYao/Long-Context-Data-Engineering/assets/76744114/2dd669cf-81e1-405c-aef3-24ea240324a6)

**Comment by ZetangForward** [comment]
> 模型为 Qwen-7B，硬件为 8*A100 80GB 使用了您提供的测试代码，张量并行，但由于不支持 FlashAttention，并没有使用FlashAttention 所能测试海底捞针的文本长度最多到10K，就OOM，想请问一下更多的细节 ![image](https://private-user-images.githubusercontent.com/76744114/324752885-2dd669cf-81e1-405c-aef3-24ea240324a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NDY5NzAsIm5iZiI6MTcxNDc0NjY3MCwicGF0aCI6Ii83Njc0NDExNC8zMjQ3NTI4ODUtMmRkNjY5Y2YtODFlMS00MDVjLWFlZjMtMjRlYTI0MDMyNGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDE0MzExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZGIzNmE0MjM2YjY4YjUwODAyMGJhYTcwODU3ZTRkY2U3YmI3MDljMzc4MmRmOTk1YzU2N2ZjNmRiNWNlZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t_fghnTapvMOfYrAenOkWPCHNMlAtLyeTGjCYGea8Oo)

您好，请问你们解决了这个问题吗？我也碰到了同样的问题。
