### ISSUE TITLE
Is there GPT_CHAR_TO_TOKEN_RATIO?

### ISSUE THREAD

**Issue by ZetangForward** [FranxYao/Long-Context-Data-Engineering#4]
Hi, thanks for your great work.
I notice there is a ``LLAMA_CHAR_TO_TOKEN_RATIO'' hyper-parameter in your script.
I want to test GPT-Neo with your script, can you provide the hyper-parameter of GPT_CHAR_TO_TOKEN_RATIO? Thx

**Comment by FranxYao** [comment]
I actually not yet tested it, but you can actually estimate it your self by letting the GPT-Neo tokenizer to tokenize, say about 500M data (does not take much time), and get the CHAR_TO_TOKEN_RATIO

**Comment by ZetangForward** [comment]
> I actually not yet tested it, but you can actually estimate it your self by letting the GPT-Neo tokenizer to tokenize, say about 500M data (does not take much time), and get the CHAR_TO_TOKEN_RATIO

ok, I will try, thx
