### ISSUE TITLE
我们对比了一下和internlm的区别，发现短文本时模型性能下降明显

### ISSUE THREAD

**Issue by esbatmop** [FranxYao/Long-Context-Data-Engineering#7]
我们使用了自己的数据，在文章的0.25、0.5、0.75三处准备的QA问答。
长文本时，llama-2-7b-80k得分略超internlm 7b
<img width="889" alt="截屏2024-03-05 15 42 21" src="https://github.com/FranxYao/Long-Context-Data-Engineering/assets/26455663/6ac086dd-1d36-4578-891d-ddabe681f76e">
短文本时，llama-2-7b-80k得分很低
<img width="869" alt="截屏2024-03-05 15 42 33" src="https://github.com/FranxYao/Long-Context-Data-Engineering/assets/26455663/aba7bf7c-b2ac-4c2b-90e5-2833ce465629">

**Comment by FranxYao** [comment]
Interesting. 这个 llama-2-7b-80k 没有经过 finetune 过，所以不一定会理解问题；请问 internLM 7B 用的是 base 还是 chat 版本？

**Comment by FranxYao** [comment]
以及能否 share 你们的测试数据？

**Comment by esbatmop** [comment]
> internLM 7B 用的是 base 还是 chat 版本

internLM 7B 用的是 chat 版本。

**Comment by esbatmop** [comment]
> 以及能否 share 你们的测试数据？

我们之前测试用的是内部数据无法分享。不过我们用开源数据重新造了测试集后复现了llama-2-7b-80k在短文本上得分比长文本低的情况（而其他模型表现恰恰相反）。晚点我把新造的数据发给你。

**Comment by FranxYao** [comment]
Hello! 

I just updated the code and fixed a previous bug on rope. The model's short-context performance should increase. Also I have updated the eval on BookQA from InfiniBench (see the updated README) which should have similar eval formats as your data

Let me know if the concern still exists

**Comment by esbatmop** [comment]
加上README 中增加的scaling_factor和seq_len的修改后，模型在短文本上得分得到了大幅度提升。
