### ISSUE TITLE
Did you use eos token inbetween two documents?

### ISSUE THREAD

**Issue by jzhang38** [FranxYao/Long-Context-Data-Engineering#9]
<img width="367" alt="Screenshot 2024-03-20 at 7 25 02 PM" src="https://github.com/FranxYao/Long-Context-Data-Engineering/assets/42993249/9983df36-98b9-4b3d-8d0b-bc9ce4481b75">

Seems that you directly concatenate two documents without using the eos token?

**Comment by FranxYao** [comment]
No I did not include the eos token, but note that there is a </s> token at the beginning, which already serves the purpose for separating two sentences

**Comment by jzhang38** [comment]
Could you elaborate more on what "there is a token at the beginning" means? Are you saying Llama tokenizer would automatically prepend bos token to each sequence being tokenized?

**Comment by jzhang38** [comment]
I checked the dataset and there is indeed a bos token at the front of every document. Closing this issue.
